README.md

The `content` field should be `String` instead of `Option<String>`.

Fix the bug of readme example

---

Cargo.toml
README.md
examples/chat_completion.rs
examples/completion.rs
examples/embedding.rs
examples/function_call.rs
examples/function_call_role.rs
src/v1/api.rs

This PR suggests a transition in the library's approach, shifting from asynchronous operations with `reqwest` and `tokio` to synchronous operations using `minreq@2`. This adjustment serves to reduce the library's size and enhance build times. Furthermore, this modification empowers simpler applications that may not require the complexities of a heavyweight asynchronous library like `tokio`.

refactor: Transition from Async to Sync Requests using minreq

---

README.md
examples/chat_completion.rs
examples/completion.rs
examples/embedding.rs
examples/function_call.rs
examples/function_call_role.rs
src/v1/audio.rs
src/v1/chat_completion.rs
src/v1/common.rs
src/v1/completion.rs
src/v1/edit.rs
src/v1/embedding.rs
src/v1/file.rs
src/v1/fine_tune.rs
src/v1/image.rs
src/v1/moderation.rs

By using chain calls to create `Request` instance, we can reduce the filling of parameters. 
Before chain call:
```rust
let req = ChatCompletionRequest {
model: chat_completion::GPT4.to_string(),
messages: vec![chat_completion::ChatCompletionMessage {
role: chat_completion::MessageRole::user,
content: String::from("What is Bitcoin?"),
name: None,
function_call: None,
}],
functions: None,
function_call: None,
temperature: 0.7,
top_p: None,
n: None,
stream: None,
stop: None,
max_tokens: None,
presence_penalty: None,
frequency_penalty: None,
logit_bias: None,
user: None,
};
```
After chain call:
```rust
let req = ChatCompletionRequest::new(
chat_completion::GPT4.to_string(),
vec![chat_completion::ChatCompletionMessage {
role: chat_completion::MessageRole::user,
content: String::from("What is …
```

feat: add chain call to create Request instance

---

src/v1/chat_completion.rs

OpenAI recently added a new `response_format` property to the request body for chat completions requests endpoint. See here: [https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format)
This allows "JSON mode" for models that allow it.
I've not looked at all the code in detail so it may not work, but is hopefully a starting point.

Add "response_format" to allow for json_object responses in chat completions

---

src/v1/chat_completion.rs

Hi,
My earlier PR was done in a bit of haste and I hadn't realized `response_format` was expecting an object. I thought I was expecting a string. My apologies!
So, I've changed it to `Value` type and it's now much better. For example:
```rust
let response_format = json!({
"type": "json_object",
});
let request = ChatCompletionRequest::new(model, prompt).response_format(response_format);
```
Tested this locally and in production and working.

Switch to serde_json::Value for the response_format type

---

examples/assistant.rs
src/v1/assistant.rs

Currently the example using Assistant API is failing because the clone of the req is not stored.
This caused the API to be OK because you were not creating the Assistant in the right way.
In the first commit i fixed the clone method assigning to a variable back, that will generate the right Assistant:
```
AssistantRequest { model: "gpt-4-1106-preview", name: None, description: Some("this is a test assistant"), instructions: Some("You are a personal math tutor. When asked a question, write and run Python code to answer the question."), tools: Some([{"type": "code_interpreter"}]), file_ids: None, metadata: None }
```
But doing so you will uncover another problem with the deserialization of the response in the `AssistantObject`.
>  Error: APIError { message: "invalid type: map, expected a …

Fix assistant api

---

src/v1/common.rs
src/v1/image.rs

This adds a `model` field to the image generation request to allow for the selection of Dall-E-3

Allow generating images with Dall-E-3

---

src/v1/chat_completion.rs

OpenAI recently added a new Beta feature to some of its models, `seed`.
See [API Reference - create chat completion - seed](https://platform.openai.com/docs/api-reference/chat/create#chat-create-seed) for details.
I have added the field to `ChatCompletionRequest` as an `Option<i64>`.
I have tested on `gpt-4-1106-preview` and it does appear to produce more consistent results, especially using `response_format: json!({ "type": "json_object" })`.

Added new (Beta) feature 'seed' to ChatCompletionRequest.

---

src/v1/chat_completion.rs

Fixes #47
This PR deprecates the fields `functions` and `function_call`, which have been declared deprecated in the official OpenAI docs.
It also implements the replacement fields `tools` and `tool_choice`.
Notes:
- Upon examining the `Function` struct in `chat_completion`, I noticed that the `parameters` field is required, even though the [documentation](https://platform.openai.com/docs/api-reference/chat/create#chat-create-functions) mentions it's optional. This should be changed in the next major version.

Deprecate `functions` and add `tools`

---

src/v1/chat_completion.rs

Completes #50 by adding the corresponding `system_fingerprint` field to the response of the request with `seed`

Add the `system_fingerprint` field to the chat completion response

---

examples/function_call.rs
examples/function_call_role.rs
src/v1/chat_completion.rs

In most cases, only a few properties of `JSONSchemaDefine` are used, and it seems cumbersome to explicitly declare other properties. I have also made modifications to the code in the examples.
Before :
```rust
Box::new(chat_completion::JSONSchemaDefine {
schema_type: Some(chat_completion::JSONSchemaType::Array),
description: Some("...".to_string()),
enum_values: None,
properties: None,
required: None,
items: Some(Box::new(chat_completion::JSONSchemaDefine {
schema_type: Some(chat_completion::JSONSchemaType::Number),
description: Some("...".to_string()),
enum_values: None,
properties: None,
required: None,
items: None,
})),
})
```
After :
```rust
Box::new(chat_completion::JSONSchemaDefine {
schema_type: Some(chat_completion::JSONSchemaType::Array),
description: Some("...".to_string()), …
```

Impl Default trait for JSONSchemaDefine

---

examples/assistant.rs
src/v1/api.rs
src/v1/assistant.rs
src/v1/message.rs
src/v1/run.rs
src/v1/thread.rs

https://github.com/dongri/openai-api-rs/issues/87

Assistant beta v2

---

src/v1/api.rs

https://github.com/dongri/openai-api-rs/issues/89
Support http timeout

Add timeout option

---

src/v1/chat_completion.rs

Adds required feature of toolchoice

Add ToolChoiceType::Required

---

README.md
examples/chat_completion.rs
examples/function_call.rs
examples/function_call_role.rs
examples/vision.rs
src/v1/chat_completion.rs

also adds parralel_tool_calls option to allow us to disable it
closes #94

Support tool_calls in message history as well as tool role

---

src/v1/api.rs

I found that if I pass socks5 string to the builder the proxy won't be used. I created a fork, tested with `reqwest::Proxy::all` and confirmed that `reqwest::Proxy::http` was the problem.

fix: route all traffic through proxy

---

src/v1/run.rs

This change introduces a structured error object for the response. Previously if there is an error such as hitting quota or running out of funds, the API will return an error message and parsing will fail because it is not a string. Now it will get properly deserialized into the "LastError" struct.

Fix for structured error message

---

Cargo.toml

This allows library to be used without adding native-tls to dependencies with:
```toml
openai-api-rs = { version = "^5.0", default-features = false, features = ["rustls"] }
```
Default usage without features is unaffected.

Add rustls feature

---

src/realtime/server_event.rs

Just received this after waiting for the initial session.created event and sending some simple voice data to the realtime API:
raw WebSocket text message:
```json
{"type":"input_audio_buffer.committed","event_id":"event_AYHl1xBb8vTEssMAzp2V4","previous_item_id":null,"item_id":"item_AYHl0tPbVU5QTPDrrpoOd"}
```
So I guess it's safe to say that the null case  should be supported.

realtime server event: InputAudioBufferCommited previous_item_id may be None / null

---

src/realtime/types.rs

Receiving "cancelled" as a ResponseStatusDetail caused a deserialization failure in one of my tests:
https://platform.openai.com/docs/api-reference/realtime-server-events/response/done

Add CancelledReason to ResponseStatusDetail

---

examples/audio_transcriptions.rs
src/v1/api.rs
src/v1/audio.rs

https://github.com/dongri/openai-api-rs/issues/143

Fix audio transcription

---

src/v1/chat_completion.rs

some openai-compatible APIs don't necessarily send the id field, is this okay to do?

make "id" an optional field on ChatCompletionResponse

---

src/v1/api.rs

when using the "rustls" feature, the reqwest client didn't actually end up using it. apparently, you also need to add `use_rustls_tls()` to the client builder. this makes sure that endpoints that need http/2 requests (like the gemini one) actually work 👍 
https://github.com/seanmonstar/reqwest/discussions/2350#discussioncomment-10020959
also sorry for uploading this twice im incredibly sleep deprived

ensure rustls is used when feature is activated

---

examples/assistant.rs
examples/audio_speech.rs
examples/audio_transcriptions.rs
examples/audio_translations.rs
examples/batch.rs
examples/chat_completion.rs
examples/completion.rs
examples/embedding.rs
examples/function_call.rs
examples/function_call_role.rs
examples/openrouter.rs
examples/vision.rs
src/v1/api.rs
src/v1/assistant.rs
src/v1/audio.rs
src/v1/chat_completion.rs
src/v1/completion.rs
src/v1/edit.rs
src/v1/embedding.rs
src/v1/file.rs
src/v1/fine_tuning.rs
src/v1/image.rs
src/v1/message.rs
src/v1/moderation.rs
src/v1/run.rs
src/v1/thread.rs

Modify it so that the response headers are set to the client headers and returned.
This is Breaking change

Add headers to client

---

src/realtime/types.rs

The Failederror struct has the following format from OpenAI
```
{
"error":{
"code":null,
"message":"The server had an error while processing your request. Sorry about that! Please contact us through our help center at help.openai.com if the error persists. (include session ID in your message: sess_BPCNZdLMHo8ERhJi0qgtq). We recommend you retry your request.",
"type":"server_error"
},
"type":"failed"
}
```
Updated struct to match
https://platform.openai.com/docs/api-reference/realtime-server-events/response/done

- Update FailedError struct to correct api schema

---

src/realtime/server_event.rs

Adding  
```
#[serde(rename = "output_audio_buffer.started")]
OutputAudioBufferStarted(OutputAudioBufferStarted),
#[serde(rename = "output_audio_buffer.stopped")]
OutputAudioBufferStopped(OutputAudioBufferStopped),
#[serde(rename = "output_audio_buffer.cleared")]
OutputAudioBufferCleared(OutputAudioBufferCleared),
```
https://platform.openai.com/docs/api-reference/realtime-server-events/output_audio_buffer

- Add output_audio_buffer.(started/stopped/cleared) server event enums
