README.md
=> Add docs and examples

Cargo.toml, examples/embedding.rs, src/v1/embedding.rs
Fix embedding response
Bug report https://github.com/dongri/openai-api-rs/issues/7
=> Fix issue 7

README.md
https://github.com/dongri/openai-api-rs/issues/9
=> Add docs.rs link

README.md, examples/chat_completion.rs, examples/function_call.rs, src/v1/chat_completion.rs
https://github.com/dongri/openai-api-rs/issues/12
=> Add parameter

examples/function_call_role.rs, src/v1/chat_completion.rs
Issue: https://github.com/dongri/openai-api-rs/issues/14
=> Add function in role

examples/chat_completion.rs, examples/completion.rs, examples/function_call.rs, examples/function_call_role.rs, src/v1/audio.rs, src/v1/chat_completion.rs, src/v1/completion.rs, src/v1/moderation.rs
https://github.com/dongri/openai-api-rs/issues/16
Remove Option<T> and Add clone for message
=> Fix required

src/v1/api.rs
https://github.com/dongri/openai-api-rs/issues/18
=> Add new_with_endpoint

Cargo.toml, README.md, src/v1/api.rs
Add default endpoint
https://github.com/dongri/openai-api-rs/issues/21
=> Endpoint from env

src/v1/api.rs
https://github.com/dongri/openai-api-rs/issues/25
=> Add new_with_organization

examples/function_call.rs, src/v1/chat_completion.rs
https://github.com/dongri/openai-api-rs/issues/33
Add function call type
=> Add function call type

examples/function_call.rs, src/v1/chat_completion.rs
https://github.com/dongri/openai-api-rs/issues/33
=> Fix function call type

src/v1/chat_completion.rs
I needed this 16k context model but saw it is not added.
=> Add "gpt-3.5-turbo-16k" model chat_completion.rs

examples/assistant.rs, examples/chat_completion.rs, examples/function_call.rs, examples/function_call_role.rs, src/v1/api.rs, src/v1/assistant.rs, src/v1/audio.rs, src/v1/chat_completion.rs, src/v1/common.rs, src/v1/completion.rs, src/v1/edit.rs, src/v1/embedding.rs, src/v1/fine_tune.rs, src/v1/image.rs, src/v1/message.rs, src/v1/mod.rs, src/v1/moderation.rs, src/v1/run.rs, src/v1/thread.rs
https://platform.openai.com/docs/api-reference/assistants
=> Add assistant api

src/v1/chat_completion.rs
Fix for https://github.com/dongri/openai-api-rs/issues/59
=> Make fields of Tool public. Rename a field.

examples/chat_completion.rs, examples/function_call.rs, examples/function_call_role.rs, src/v1/chat_completion.rs
=> Fix Deprecated

examples/chat_completion.rs, examples/function_call.rs, examples/function_call_role.rs, examples/vision.rs, src/v1/chat_completion.rs
=> Add vision

src/v1/chat_completion.rs, src/v1/message.rs, src/v1/thread.rs
https://github.com/dongri/openai-api-rs/issues/75
=> Add eq trait

examples/chat_completion.rs, src/v1/api.rs, src/v1/assistant.rs, src/v1/audio.rs, src/v1/chat_completion.rs, src/v1/completion.rs, src/v1/edit.rs, src/v1/embedding.rs, src/v1/file.rs, src/v1/fine_tuning.rs, src/v1/image.rs, src/v1/message.rs, src/v1/moderation.rs, src/v1/run.rs, src/v1/thread.rs
https://github.com/dongri/openai-api-rs/issues/80
=> Add response header

README.md, examples/chat_completion.rs, examples/function_call.rs, examples/function_call_role.rs, examples/vision.rs, src/v1/chat_completion.rs
Allows us to deserialize ChatCompletionMessage, so that we can store and retrieve it from a string.
=> Adds deserializer for Content

src/v1/run.rs
Issue: https://github.com/dongri/openai-api-rs/issues/100
=> Add response_format

Cargo.toml
https://github.com/dongri/openai-api-rs/pull/67#issuecomment-2289417640
=> Add socks feature for reqwest

Cargo.toml, examples/batch.rs, examples/data/batch_request.json, examples/data/batch_result.json, src/v1/api.rs, src/v1/batch.rs, src/v1/common.rs, src/v1/file.rs, src/v1/mod.rs
https://github.com/dongri/openai-api-rs/issues/106
=> Add batch api

examples/vision.rs
GPT4-VISION-PREVIEW is no longer available, update to GPT-4O
=> Vision example update 

src/v1/embedding.rs, src/v1/image.rs
I am using this crate for a proxy, and I need to take requests and resend them. Adding the deserialization makes my life easier!
=> Add derive Deserialize to ImageRequest and EmbeddingRequest

examples/embedding.rs, src/v1/embedding.rs
https://github.com/dongri/openai-api-rs/issues/120
=> Fix input type for embedding

src/v1/assistant.rs, src/v1/run.rs, src/v1/types.rs
https://github.com/dongri/openai-api-rs/issues/125
=> Fix run object

src/v1/message.rs
https://github.com/dongri/openai-api-rs/issues/127
=> Add ContentTextAnnotations

examples/audio_transcriptions.rs, src/v1/api.rs
Fix https://github.com/dongri/openai-api-rs/issues/133
=> Add post_form_raw

Cargo.toml, src/v1/api.rs
In some APIs eg azure the auth headers are optional and you required api-key as header.
=> Optional auth header and with api keys | works with azure

examples/chat_completion.rs, examples/model.rs, examples/openrouter.rs, src/v1/api.rs, src/v1/assistant.rs, src/v1/common.rs, src/v1/mod.rs, src/v1/model.rs
Fix issue
https://github.com/dongri/openai-api-rs/issues/165
https://github.com/dongri/openai-api-rs/issues/163
=> Add models api

examples/batch.rs, examples/function_call.rs, examples/function_call_role.rs, src/v1/api.rs, src/v1/batch.rs, src/v1/error.rs
Fix this issue
https://github.com/dongri/openai-api-rs/issues/171
document
https://platform.openai.com/docs/api-reference/batch/object
=> Fix batch object

examples/openrouter_models.rs, src/v1/model.rs
https://github.com/dongri/openai-api-rs/issues/175
=> Fix model struct

src/v1/chat_completion.rs
Add optional transforms field to enable request preprocessing.
https://openrouter.ai/docs/features/message-transforms
=> ✨ feat: add transforms field to ChatCompletionRequest

.github/workflows/rust-check.yml, src/v1/common.rs
https://github.com/dongri/openai-api-rs/issues/180
=> Fix models
